export const uiPalette = {
  canvas: "#ffffff",
  canvasRaised: "#ffffff",
  surface: "#ffffff",
  surfaceMuted: "#ffffff",
  surfaceStrong: "#ffffff",
  line: "#ece8e1",
  lineStrong: "#ddd7cf",
  ink: "#22212a",
  inkStrong: "#17161d",
  inkMuted: "#7d7887",
  inkSoft: "#a59eaa",
  cobalt: "#4f5fff",
  cobaltPressed: "#3f50eb",
  cobaltSoft: "#eef0ff",
  cobaltLine: "#d7dcff",
  lilac: "#cbb8ff",
  lilacSoft: "#f4eeff",
  lilacLine: "#e4d8ff",
  success: "#2f7d5a",
  successSoft: "#e7f4ed",
  successLine: "#cfe5d9",
  warning: "#b9781f",
  warningSoft: "#faf0df",
  warningLine: "#edd9b8",
  danger: "#c34b59",
  dangerSoft: "#faecee",
  dangerLine: "#efcfd5",
  shadow: "rgba(23, 22, 29, 0.08)",
  shadowStrong: "rgba(23, 22, 29, 0.38)",
} as const

export const memberAccentPalette = [
  "#4f5fff",
  "#7a8aff",
  "#cbb8ff",
  "#9b7df0",
  "#5c77d8",
  "#7ea3ff",
] as const
