export const COPY = {
  auth: {
    testAccountLabel: "테스트 계정: test@test.com / password",
  },
  notification: {
    title: "알림 설정",
    subtitle: "회비 마감/거래/공지 알림을 관리합니다.",
    saved: "알림 설정을 저장했습니다.",
  },
  account: {
    createTitle: "모임통장 개설",
    createSubtitle: "새로운 모임통장을 만들어보세요.",
    createSuccess: "새 모임통장을 만들었습니다.",
    createEmptyTitle: "아직 모임통장이 없어요",
    createEmptyDescription: "새 모임통장을 열고 회비 관리를 시작하세요.",
    createButtonLabel: "+ 새 모임통장 개설",
    copyAccountNumber: "계좌번호를 복사했습니다.",
    copyAccountNumberFail: "계좌번호를 복사하지 못했습니다.",
    deleteLabel: "이 모임통장 삭제",
    emptyTitle: "선택된 모임이 없습니다.",
    emptyDescription: "목록에서 모임통장을 다시 선택해주세요.",
  },
  dues: {
    reminderSent: (name: string) => `${name}님께 납부 안내를 보냈습니다.`,
    reminderSentTitle: "납부 안내 전송",
    transferRequestSent: (name: string) => `${name}님께 이체 요청을 보냈습니다.`,
    transferRequestSentTitle: "이체 요청 전송",
    markPaid: "완납 처리",
    cancelPaid: "취소",
  },
  common: {
    cancel: "취소",
    edit: "수정",
    delete: "삭제",
    save: "저장",
    saving: "저장 중...",
    saveDone: "저장 완료",
    editDone: "수정 완료",
    deleteDone: "삭제 완료",
    addDone: "추가 완료",
    registerDone: "등록 완료",
    processing: "처리 중...",
    inputError: "입력 오류",
  },
  member: {
    addTitle: "새 멤버 추가",
    editTitle: "멤버 수정",
    deleteTitle: "멤버 삭제",
    delegateTitle: "총무 위임",
    addDone: "새 멤버를 등록했습니다.",
    editDone: "멤버 정보를 수정했습니다.",
    deleteDone: "멤버를 제거했습니다.",
    delegateDone: (name: string) => `${name}님이 새로운 총무가 되었습니다.`,
    addButtonLabel: "멤버 추가",
    editButtonLabel: "멤버 수정",
    submittingAdd: "처리 중...",
    submittingEdit: "처리 중...",
  },
  board: {
    postTitle: "게시글 작성",
    editPostTitle: "수정 저장",
    deletePostTitle: "게시글 삭제",
    deleteCommentTitle: "댓글 삭제",
    commentLabel: "댓글",
    commentEditLabel: "댓글 수정",
    postDone: "게시판에 새 글을 올렸습니다.",
    postEditDone: "게시글을 수정했습니다.",
    postDeleteDone: "게시글을 삭제했습니다.",
    commentAddDone: "댓글을 남겼습니다.",
    commentEditDone: "댓글을 수정했습니다.",
    commentDeleteDone: "댓글을 삭제했습니다.",
    commentRegisterTitle: "댓글 등록",
    postDoneTitle: "게시 완료",
    posting: "게시 중...",
  },
  transaction: {
    newTitle: "새 거래 등록",
    editTitle: "거래 수정",
    deleteTitle: "거래 삭제",
    income: "입금",
    expense: "출금",
    editDone: (desc: string) => `${desc} 거래를 수정했습니다.`,
    registerDone: (desc: string) => `${desc} 거래를 추가했습니다.`,
    deleteDone: (desc: string) => `${desc} 거래를 제거했습니다.`,
    editButtonLabel: "거래 수정",
    cancelEditLabel: "편집 취소",
    incomeRegisterLabel: "입금 등록",
    expenseRegisterLabel: "출금 등록",
    savingLabel: "저장 중...",
  },
} as const
